services:
  discovery:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
      context: ..
    networks:
      test_net:
        ipv4_address: 172.20.0.2
    command: fastdds discovery --server-id 0

  chatter:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
      context: ..
    environment:
      - ROS_DISCOVERY_SERVER=172.20.0.2:11811
      - FASTRTPS_DEFAULT_PROFILES_FILE=/super_client.xml
    depends_on:
      - discovery
    networks:
      test_net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./super_client.xml:/super_client.xml:ro
    command: |
      ros2 topic pub /chatter std_msgs/msg/String "{data: 'Hello World!'}"

  listener:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
      context: ..
    environment:
      - ROS_DISCOVERY_SERVER=172.20.0.2:11811
      - FASTRTPS_DEFAULT_PROFILES_FILE=/super_client.xml
    depends_on:
      - discovery
    networks:
      test_net:
        ipv4_address: 172.20.0.4
    volumes:
      - ./super_client.xml:/super_client.xml:ro
    command: |
      ros2 topic echo /chatter std_msgs/msg/String

  scrambler:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
      context: ..
    environment:
      - ROS_DISCOVERY_SERVER=172.20.0.2:11811
    depends_on:
      - discovery
    networks:
      test_net:
        ipv4_address: 172.20.0.5
    volumes:
      - ./scrambler.launch.xml:/scrambler.launch.xml:ro
    command: |
      ros2 launch /scrambler.launch.xml

networks:
  test_net:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 172.20.0.0/16
