services:
  discovery:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      context: ..
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
    environment:
      - ROS2_EASY_MODE=172.20.0.2
    networks:
      test_net:
        ipv4_address: 172.20.0.2
    command: fastdds discovery --server-id 0

  chatter:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      context: ..
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
    environment:
      - ROS2_EASY_MODE=172.20.0.2
    depends_on:
      - discovery
    networks:
      test_net:
        ipv4_address: 172.20.0.3
    command: |
      ros2 topic pub /chatter std_msgs/msg/String "{data: 'Hello World!'}"

  listener:
    image: fastdds_discovery_sandbox:${ROS_DISTRO:-jazzy}
    build:
      dockerfile: dockerfile
      context: ..
      args:
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
    environment:
      - ROS2_EASY_MODE=172.20.0.2
    depends_on:
      - discovery
    networks:
      test_net:
        ipv4_address: 172.20.0.4
    command: |
      ros2 topic echo /chatter std_msgs/msg/String

networks:
  test_net:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 172.20.0.0/16
